### ISSUE TITLE
Melhorar descrição README

### ISSUE THREAD

**Issue by AramisAraujo** [herculesra/ProjetoDevWeb#1]
A ideia parece bem interessante, mas acredito que você deve detalhar o propósito do usuário no seu projeto : há apenas compra? quem faz o cadastro dos giftcards?

Fica como sugestão a funcionalidade de realizar um sorteio a partir da compra do giftcard.

**Comment by herculesra** [comment]
As funcionalidades de usuários e adm será um caso a ser pensado para o propósito do projeto. A ideia geral será mostrar como o sistema funciona sem estas partes, mas não deixam de ser um futuro upgrade a ser pensado. =)
