### ISSUE TITLE
Organização dos components, nome e pastas

### ISSUE THREAD

**Issue by davidedup** [herculesra/ProjetoDevWeb#2]
Tu  ta colocando cada component numa pasta e chamando de index.js. Talvez organizar as pastas por contexto e dar nome a cada componente seja melhor

Um exemplo aqui: https://github.com/alvesmatheus/clow-cards/tree/master/client/src/components

**Comment by herculesra** [comment]
Obrigado pela dica, mas continuarei com o padrão utilizado,  é um padrão utilizado por grandes empresas como a Rocketseat, por exemplo.
O nome das pastas representam o componente, por isso começam com letras maiúsculas. Dentro de cada pasta que representa o componente temos 2 arquivos: index.jsx e o styles.css, que são respectivamente, o arquivo da lógica do componente e a folha de estilo atrelado à ele.
