### ISSUE TITLE
Gift Model

### ISSUE THREAD

**Issue by camilacarvalho** [herculesra/ProjetoDevWeb#3]
https://github.com/herculesra/ProjetoDevWeb/blob/008b3eb9f37acd5c0552738da1bbdbd66ec01461/frontend/src/pages/Home/index.jsx#L31-L39

Primeiro eu queria dizer que goestei muito da organização do projeto. Como sugestão acredito que seria interessante criar um model para o gift, assim ao invés do componente card ter vários props ele teria apenas um props. Acho que fica mais organizado e mais fácil de compreender.

**Comment by herculesra** [comment]
Massa! Vou dar uma olhada sobre. :D

**Comment by herculesra** [comment]
Feito =D
