### ISSUE TITLE
Sugestão de Mundaça - Criação de Instâncias de CardModel

### ISSUE THREAD

**Issue by mateusqc** [herculesra/ProjetoDevWeb#6]
Olá, Hércules! Inicialmente, meus parabéns pelo ótimo código. Muito bem organizado. Tenho apenas uma sugestão de mudança no componente da página inicial. Nesse componente você está fazendo a criação de novas instâncias de cardModels no render, conforme a linha abaixo:

https://github.com/herculesra/ProjetoDevWeb/blob/1d281257a46d3ee52605cdc52d850d7c36f352b7/frontend/src/pages/Home/index.jsx#L39

Esta decisão não está incorreta, mas talvez essa instanciação ficasse melhor sendo feita na função `fetchDataApi`, logo antes de passar os dados para o state do componente:

https://github.com/herculesra/ProjetoDevWeb/blob/1d281257a46d3ee52605cdc52d850d7c36f352b7/frontend/src/pages/Home/index.jsx#L26

Dessa forma, as operações de carregamento e instanciação dos objetos da lista ficarão num mesmo contexto e você já guardará a lista de objetos bem definidos no seu state.

**Comment by herculesra** [comment]
Oi @mateusqc  obrigado pela dica! Mas se eu colocar a instanciação como vc recomenda terei que criar alguma estrutura para armazenar estas para logo depois, no render, utilizá-la para mostrar estas instâncias. Seria isso?

**Comment by herculesra** [comment]
Implementado, @mateusqc. :)

**Comment by mateusqc** [comment]
> Oi @mateusqc obrigado pela dica! Mas se eu colocar a instanciação como vc recomenda terei que criar alguma estrutura para armazenar estas para logo depois, no render, utilizá-la para mostrar estas instâncias. Seria isso?

Desculpe a demora, @herculesra! Perfeito, seria exatamente isso daí mesmo.
